<?php
/**
 * ISO 3166-1 alpha-2 English country names for the simulation selector.
 *
 * @package UniversalGeoContext
 */

declare( strict_types=1 );

namespace UniversalGeo\Simulation;

/**
 * Static ISO country label catalogue for the simulation selector.
 *
 * @internal
 * @final
 */
final class CountryNames {

	/**
	 * English labels keyed by ISO alpha-2 code.
	 *
	 * @return array<string, string>
	 */
	public static function labels(): array {
		return array(
			'AF' => __( 'Afghanistan', 'universal-geo-context' ),
			'AL' => __( 'Albania', 'universal-geo-context' ),
			'DZ' => __( 'Algeria', 'universal-geo-context' ),
			'AS' => __( 'American Samoa', 'universal-geo-context' ),
			'AD' => __( 'Andorra', 'universal-geo-context' ),
			'AO' => __( 'Angola', 'universal-geo-context' ),
			'AI' => __( 'Anguilla', 'universal-geo-context' ),
			'AQ' => __( 'Antarctica', 'universal-geo-context' ),
			'AG' => __( 'Antigua and Barbuda', 'universal-geo-context' ),
			'AR' => __( 'Argentina', 'universal-geo-context' ),
			'AM' => __( 'Armenia', 'universal-geo-context' ),
			'AW' => __( 'Aruba', 'universal-geo-context' ),
			'AU' => __( 'Australia', 'universal-geo-context' ),
			'AT' => __( 'Austria', 'universal-geo-context' ),
			'AZ' => __( 'Azerbaijan', 'universal-geo-context' ),
			'BS' => __( 'Bahamas', 'universal-geo-context' ),
			'BH' => __( 'Bahrain', 'universal-geo-context' ),
			'BD' => __( 'Bangladesh', 'universal-geo-context' ),
			'BB' => __( 'Barbados', 'universal-geo-context' ),
			'BY' => __( 'Belarus', 'universal-geo-context' ),
			'BE' => __( 'Belgium', 'universal-geo-context' ),
			'BZ' => __( 'Belize', 'universal-geo-context' ),
			'BJ' => __( 'Benin', 'universal-geo-context' ),
			'BM' => __( 'Bermuda', 'universal-geo-context' ),
			'BT' => __( 'Bhutan', 'universal-geo-context' ),
			'BO' => __( 'Bolivia, Plurinational State of', 'universal-geo-context' ),
			'BQ' => __( 'Bonaire, Sint Eustatius and Saba', 'universal-geo-context' ),
			'BA' => __( 'Bosnia and Herzegovina', 'universal-geo-context' ),
			'BW' => __( 'Botswana', 'universal-geo-context' ),
			'BV' => __( 'Bouvet Island', 'universal-geo-context' ),
			'BR' => __( 'Brazil', 'universal-geo-context' ),
			'IO' => __( 'British Indian Ocean Territory', 'universal-geo-context' ),
			'BN' => __( 'Brunei Darussalam', 'universal-geo-context' ),
			'BG' => __( 'Bulgaria', 'universal-geo-context' ),
			'BF' => __( 'Burkina Faso', 'universal-geo-context' ),
			'BI' => __( 'Burundi', 'universal-geo-context' ),
			'CV' => __( 'Cabo Verde', 'universal-geo-context' ),
			'KH' => __( 'Cambodia', 'universal-geo-context' ),
			'CM' => __( 'Cameroon', 'universal-geo-context' ),
			'CA' => __( 'Canada', 'universal-geo-context' ),
			'KY' => __( 'Cayman Islands', 'universal-geo-context' ),
			'CF' => __( 'Central African Republic', 'universal-geo-context' ),
			'TD' => __( 'Chad', 'universal-geo-context' ),
			'CL' => __( 'Chile', 'universal-geo-context' ),
			'CN' => __( 'China', 'universal-geo-context' ),
			'CX' => __( 'Christmas Island', 'universal-geo-context' ),
			'CC' => __( 'Cocos (Keeling) Islands', 'universal-geo-context' ),
			'CO' => __( 'Colombia', 'universal-geo-context' ),
			'KM' => __( 'Comoros', 'universal-geo-context' ),
			'CG' => __( 'Congo', 'universal-geo-context' ),
			'CD' => __( 'Congo, Democratic Republic of the', 'universal-geo-context' ),
			'CK' => __( 'Cook Islands', 'universal-geo-context' ),
			'CR' => __( 'Costa Rica', 'universal-geo-context' ),
			'HR' => __( 'Croatia', 'universal-geo-context' ),
			'CU' => __( 'Cuba', 'universal-geo-context' ),
			'CW' => __( 'Curaçao', 'universal-geo-context' ),
			'CY' => __( 'Cyprus', 'universal-geo-context' ),
			'CZ' => __( 'Czechia', 'universal-geo-context' ),
			'CI' => __( 'Côte d\'Ivoire', 'universal-geo-context' ),
			'DK' => __( 'Denmark', 'universal-geo-context' ),
			'DJ' => __( 'Djibouti', 'universal-geo-context' ),
			'DM' => __( 'Dominica', 'universal-geo-context' ),
			'DO' => __( 'Dominican Republic', 'universal-geo-context' ),
			'EC' => __( 'Ecuador', 'universal-geo-context' ),
			'EG' => __( 'Egypt', 'universal-geo-context' ),
			'SV' => __( 'El Salvador', 'universal-geo-context' ),
			'GQ' => __( 'Equatorial Guinea', 'universal-geo-context' ),
			'ER' => __( 'Eritrea', 'universal-geo-context' ),
			'EE' => __( 'Estonia', 'universal-geo-context' ),
			'SZ' => __( 'Eswatini', 'universal-geo-context' ),
			'ET' => __( 'Ethiopia', 'universal-geo-context' ),
			'FK' => __( 'Falkland Islands (Malvinas)', 'universal-geo-context' ),
			'FO' => __( 'Faroe Islands', 'universal-geo-context' ),
			'FJ' => __( 'Fiji', 'universal-geo-context' ),
			'FI' => __( 'Finland', 'universal-geo-context' ),
			'FR' => __( 'France', 'universal-geo-context' ),
			'GF' => __( 'French Guiana', 'universal-geo-context' ),
			'PF' => __( 'French Polynesia', 'universal-geo-context' ),
			'TF' => __( 'French Southern Territories', 'universal-geo-context' ),
			'GA' => __( 'Gabon', 'universal-geo-context' ),
			'GM' => __( 'Gambia', 'universal-geo-context' ),
			'GE' => __( 'Georgia', 'universal-geo-context' ),
			'DE' => __( 'Germany', 'universal-geo-context' ),
			'GH' => __( 'Ghana', 'universal-geo-context' ),
			'GI' => __( 'Gibraltar', 'universal-geo-context' ),
			'GR' => __( 'Greece', 'universal-geo-context' ),
			'GL' => __( 'Greenland', 'universal-geo-context' ),
			'GD' => __( 'Grenada', 'universal-geo-context' ),
			'GP' => __( 'Guadeloupe', 'universal-geo-context' ),
			'GU' => __( 'Guam', 'universal-geo-context' ),
			'GT' => __( 'Guatemala', 'universal-geo-context' ),
			'GG' => __( 'Guernsey', 'universal-geo-context' ),
			'GN' => __( 'Guinea', 'universal-geo-context' ),
			'GW' => __( 'Guinea-Bissau', 'universal-geo-context' ),
			'GY' => __( 'Guyana', 'universal-geo-context' ),
			'HT' => __( 'Haiti', 'universal-geo-context' ),
			'HM' => __( 'Heard Island and McDonald Islands', 'universal-geo-context' ),
			'VA' => __( 'Holy See', 'universal-geo-context' ),
			'HN' => __( 'Honduras', 'universal-geo-context' ),
			'HK' => __( 'Hong Kong', 'universal-geo-context' ),
			'HU' => __( 'Hungary', 'universal-geo-context' ),
			'IS' => __( 'Iceland', 'universal-geo-context' ),
			'IN' => __( 'India', 'universal-geo-context' ),
			'ID' => __( 'Indonesia', 'universal-geo-context' ),
			'IR' => __( 'Iran, Islamic Republic of', 'universal-geo-context' ),
			'IQ' => __( 'Iraq', 'universal-geo-context' ),
			'IE' => __( 'Ireland', 'universal-geo-context' ),
			'IM' => __( 'Isle of Man', 'universal-geo-context' ),
			'IL' => __( 'Israel', 'universal-geo-context' ),
			'IT' => __( 'Italy', 'universal-geo-context' ),
			'JM' => __( 'Jamaica', 'universal-geo-context' ),
			'JP' => __( 'Japan', 'universal-geo-context' ),
			'JE' => __( 'Jersey', 'universal-geo-context' ),
			'JO' => __( 'Jordan', 'universal-geo-context' ),
			'KZ' => __( 'Kazakhstan', 'universal-geo-context' ),
			'KE' => __( 'Kenya', 'universal-geo-context' ),
			'KI' => __( 'Kiribati', 'universal-geo-context' ),
			'KP' => __( 'Korea, Democratic People\'s Republic of', 'universal-geo-context' ),
			'KR' => __( 'Korea, Republic of', 'universal-geo-context' ),
			'XK' => __( 'Kosovo', 'universal-geo-context' ),
			'KW' => __( 'Kuwait', 'universal-geo-context' ),
			'KG' => __( 'Kyrgyzstan', 'universal-geo-context' ),
			'LA' => __( 'Lao People\'s Democratic Republic', 'universal-geo-context' ),
			'LV' => __( 'Latvia', 'universal-geo-context' ),
			'LB' => __( 'Lebanon', 'universal-geo-context' ),
			'LS' => __( 'Lesotho', 'universal-geo-context' ),
			'LR' => __( 'Liberia', 'universal-geo-context' ),
			'LY' => __( 'Libya', 'universal-geo-context' ),
			'LI' => __( 'Liechtenstein', 'universal-geo-context' ),
			'LT' => __( 'Lithuania', 'universal-geo-context' ),
			'LU' => __( 'Luxembourg', 'universal-geo-context' ),
			'MO' => __( 'Macao', 'universal-geo-context' ),
			'MG' => __( 'Madagascar', 'universal-geo-context' ),
			'MW' => __( 'Malawi', 'universal-geo-context' ),
			'MY' => __( 'Malaysia', 'universal-geo-context' ),
			'MV' => __( 'Maldives', 'universal-geo-context' ),
			'ML' => __( 'Mali', 'universal-geo-context' ),
			'MT' => __( 'Malta', 'universal-geo-context' ),
			'MH' => __( 'Marshall Islands', 'universal-geo-context' ),
			'MQ' => __( 'Martinique', 'universal-geo-context' ),
			'MR' => __( 'Mauritania', 'universal-geo-context' ),
			'MU' => __( 'Mauritius', 'universal-geo-context' ),
			'YT' => __( 'Mayotte', 'universal-geo-context' ),
			'MX' => __( 'Mexico', 'universal-geo-context' ),
			'FM' => __( 'Micronesia, Federated States of', 'universal-geo-context' ),
			'MD' => __( 'Moldova, Republic of', 'universal-geo-context' ),
			'MC' => __( 'Monaco', 'universal-geo-context' ),
			'MN' => __( 'Mongolia', 'universal-geo-context' ),
			'ME' => __( 'Montenegro', 'universal-geo-context' ),
			'MS' => __( 'Montserrat', 'universal-geo-context' ),
			'MA' => __( 'Morocco', 'universal-geo-context' ),
			'MZ' => __( 'Mozambique', 'universal-geo-context' ),
			'MM' => __( 'Myanmar', 'universal-geo-context' ),
			'NA' => __( 'Namibia', 'universal-geo-context' ),
			'NR' => __( 'Nauru', 'universal-geo-context' ),
			'NP' => __( 'Nepal', 'universal-geo-context' ),
			'NL' => __( 'Netherlands, Kingdom of the', 'universal-geo-context' ),
			'NC' => __( 'New Caledonia', 'universal-geo-context' ),
			'NZ' => __( 'New Zealand', 'universal-geo-context' ),
			'NI' => __( 'Nicaragua', 'universal-geo-context' ),
			'NE' => __( 'Niger', 'universal-geo-context' ),
			'NG' => __( 'Nigeria', 'universal-geo-context' ),
			'NU' => __( 'Niue', 'universal-geo-context' ),
			'NF' => __( 'Norfolk Island', 'universal-geo-context' ),
			'MK' => __( 'North Macedonia', 'universal-geo-context' ),
			'MP' => __( 'Northern Mariana Islands', 'universal-geo-context' ),
			'NO' => __( 'Norway', 'universal-geo-context' ),
			'OM' => __( 'Oman', 'universal-geo-context' ),
			'PK' => __( 'Pakistan', 'universal-geo-context' ),
			'PW' => __( 'Palau', 'universal-geo-context' ),
			'PS' => __( 'Palestine, State of', 'universal-geo-context' ),
			'PA' => __( 'Panama', 'universal-geo-context' ),
			'PG' => __( 'Papua New Guinea', 'universal-geo-context' ),
			'PY' => __( 'Paraguay', 'universal-geo-context' ),
			'PE' => __( 'Peru', 'universal-geo-context' ),
			'PH' => __( 'Philippines', 'universal-geo-context' ),
			'PN' => __( 'Pitcairn', 'universal-geo-context' ),
			'PL' => __( 'Poland', 'universal-geo-context' ),
			'PT' => __( 'Portugal', 'universal-geo-context' ),
			'PR' => __( 'Puerto Rico', 'universal-geo-context' ),
			'QA' => __( 'Qatar', 'universal-geo-context' ),
			'RO' => __( 'Romania', 'universal-geo-context' ),
			'RU' => __( 'Russian Federation', 'universal-geo-context' ),
			'RW' => __( 'Rwanda', 'universal-geo-context' ),
			'RE' => __( 'Réunion', 'universal-geo-context' ),
			'BL' => __( 'Saint Barthélemy', 'universal-geo-context' ),
			'SH' => __( 'Saint Helena, Ascension and Tristan da Cunha', 'universal-geo-context' ),
			'KN' => __( 'Saint Kitts and Nevis', 'universal-geo-context' ),
			'LC' => __( 'Saint Lucia', 'universal-geo-context' ),
			'MF' => __( 'Saint Martin (French part)', 'universal-geo-context' ),
			'PM' => __( 'Saint Pierre and Miquelon', 'universal-geo-context' ),
			'VC' => __( 'Saint Vincent and the Grenadines', 'universal-geo-context' ),
			'WS' => __( 'Samoa', 'universal-geo-context' ),
			'SM' => __( 'San Marino', 'universal-geo-context' ),
			'ST' => __( 'Sao Tome and Principe', 'universal-geo-context' ),
			'SA' => __( 'Saudi Arabia', 'universal-geo-context' ),
			'SN' => __( 'Senegal', 'universal-geo-context' ),
			'RS' => __( 'Serbia', 'universal-geo-context' ),
			'SC' => __( 'Seychelles', 'universal-geo-context' ),
			'SL' => __( 'Sierra Leone', 'universal-geo-context' ),
			'SG' => __( 'Singapore', 'universal-geo-context' ),
			'SX' => __( 'Sint Maarten (Dutch part)', 'universal-geo-context' ),
			'SK' => __( 'Slovakia', 'universal-geo-context' ),
			'SI' => __( 'Slovenia', 'universal-geo-context' ),
			'SB' => __( 'Solomon Islands', 'universal-geo-context' ),
			'SO' => __( 'Somalia', 'universal-geo-context' ),
			'ZA' => __( 'South Africa', 'universal-geo-context' ),
			'GS' => __( 'South Georgia and the South Sandwich Islands', 'universal-geo-context' ),
			'SS' => __( 'South Sudan', 'universal-geo-context' ),
			'ES' => __( 'Spain', 'universal-geo-context' ),
			'LK' => __( 'Sri Lanka', 'universal-geo-context' ),
			'SD' => __( 'Sudan', 'universal-geo-context' ),
			'SR' => __( 'Suriname', 'universal-geo-context' ),
			'SJ' => __( 'Svalbard and Jan Mayen', 'universal-geo-context' ),
			'SE' => __( 'Sweden', 'universal-geo-context' ),
			'CH' => __( 'Switzerland', 'universal-geo-context' ),
			'SY' => __( 'Syrian Arab Republic', 'universal-geo-context' ),
			'TW' => __( 'Taiwan, Province of China', 'universal-geo-context' ),
			'TJ' => __( 'Tajikistan', 'universal-geo-context' ),
			'TZ' => __( 'Tanzania, United Republic of', 'universal-geo-context' ),
			'TH' => __( 'Thailand', 'universal-geo-context' ),
			'TL' => __( 'Timor-Leste', 'universal-geo-context' ),
			'TG' => __( 'Togo', 'universal-geo-context' ),
			'TK' => __( 'Tokelau', 'universal-geo-context' ),
			'TO' => __( 'Tonga', 'universal-geo-context' ),
			'TT' => __( 'Trinidad and Tobago', 'universal-geo-context' ),
			'TN' => __( 'Tunisia', 'universal-geo-context' ),
			'TM' => __( 'Turkmenistan', 'universal-geo-context' ),
			'TC' => __( 'Turks and Caicos Islands', 'universal-geo-context' ),
			'TV' => __( 'Tuvalu', 'universal-geo-context' ),
			'TR' => __( 'Türkiye', 'universal-geo-context' ),
			'UG' => __( 'Uganda', 'universal-geo-context' ),
			'UA' => __( 'Ukraine', 'universal-geo-context' ),
			'AE' => __( 'United Arab Emirates', 'universal-geo-context' ),
			'GB' => __( 'United Kingdom of Great Britain and Northern Ireland', 'universal-geo-context' ),
			'UM' => __( 'United States Minor Outlying Islands', 'universal-geo-context' ),
			'US' => __( 'United States of America', 'universal-geo-context' ),
			'UY' => __( 'Uruguay', 'universal-geo-context' ),
			'UZ' => __( 'Uzbekistan', 'universal-geo-context' ),
			'VU' => __( 'Vanuatu', 'universal-geo-context' ),
			'VE' => __( 'Venezuela, Bolivarian Republic of', 'universal-geo-context' ),
			'VN' => __( 'Viet Nam', 'universal-geo-context' ),
			'VG' => __( 'Virgin Islands (British)', 'universal-geo-context' ),
			'VI' => __( 'Virgin Islands (U.S.)', 'universal-geo-context' ),
			'WF' => __( 'Wallis and Futuna', 'universal-geo-context' ),
			'EH' => __( 'Western Sahara', 'universal-geo-context' ),
			'YE' => __( 'Yemen', 'universal-geo-context' ),
			'ZM' => __( 'Zambia', 'universal-geo-context' ),
			'ZW' => __( 'Zimbabwe', 'universal-geo-context' ),
			'AX' => __( 'Åland Islands', 'universal-geo-context' ),
		);
	}
}
